let myInt=55;
let myFloat=55.55;
console.log(myInt);
console.log(myFloat);
console.log("TYPEOF OPERATOR: it returns data type of that variable");
console.log("typeof(myfloat) returns type of that variable");
console.log(typeof(myFloat));
console.log("USEFUL NUMBER METHODS:");
console.log("tofixed():");
const lot_of_decimal=1.0000056789302346890;
console.log(lot_of_decimal.toFixed(2));
console.log("number constructor:constructor to return a number version of the same value");
let number="66";
console.log(Number(number));
console.log(typeof(Number(number)));
console.log("arthmetic operator:");
const num1 = 10;
const num2 = 50;
console.log(9 * num1);
console.log(num1 ** 3);
console.log(num2 / num1);
console.log("increment and decrement operator:");
let incre=55;
incre++;
console.log(incre);
console.log("assignment operator:");
incre+=55;
console.log(incre);